/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package instantmessenger;

import java.awt.LayoutManager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author manasi
 */
public class IMInterface extends javax.swing.JApplet {
    private LayoutManager FlowLayout;
    ArrayList<ChatMessage> chats = new ArrayList<ChatMessage>();
    ChatMessage chatMessage;

    /**
     * Initializes the applet IMInterface
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
                
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                @Override
                public void run() {
                    initComponents();
                }
            });
        } catch (InterruptedException | InvocationTargetException ex) {
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        BackgroundPanel = new javax.swing.JPanel();
        UserMessageText = new javax.swing.JTextField();
        SendMessageButton = new javax.swing.JButton();
        StatusMessageComboBox = new javax.swing.JComboBox();
        VoiceCallButton = new javax.swing.JButton();
        TranscriptScrollPanel = new javax.swing.JScrollPane();
        SearchContactTextBox = new javax.swing.JTextField();
        SaveChatButton = new javax.swing.JButton();
        MoreActionsComboBox = new javax.swing.JComboBox();
        ContactsScrollPanel = new javax.swing.JScrollPane();
        SearchContactTextBox1 = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        UserMessageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMessageTextActionPerformed(evt);
            }
        });

        SendMessageButton.setText("Send");
        SendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessageButtonActionPerformed(evt);
            }
        });

        StatusMessageComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Busy", " " }));
        StatusMessageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusMessageComboBoxActionPerformed(evt);
            }
        });

        VoiceCallButton.setText("Voice call");
        VoiceCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoiceCallButtonActionPerformed(evt);
            }
        });

        TranscriptScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        TranscriptScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TranscriptScrollPanel.setToolTipText("");
        TranscriptScrollPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TranscriptScrollPanelComponentAdded(evt);
            }
        });

        SearchContactTextBox.setText("Search Contact...");
        SearchContactTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchContactTextBoxActionPerformed(evt);
            }
        });

        SaveChatButton.setText("Save Chat");

        MoreActionsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "More actions", "Load Previous Chat" }));

        SearchContactTextBox1.setText("Add Contact...");
        SearchContactTextBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchContactTextBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchContactTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactsScrollPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(SearchContactTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(StatusMessageComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(VoiceCallButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveChatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MoreActionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SendMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserMessageText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TranscriptScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(TranscriptScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VoiceCallButton)
                            .addComponent(SaveChatButton)
                            .addComponent(MoreActionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserMessageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SendMessageButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(SearchContactTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(SearchContactTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatusMessageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactsScrollPanel)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchContactTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchContactTextBoxActionPerformed
      
    }//GEN-LAST:event_SearchContactTextBoxActionPerformed

    private void VoiceCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoiceCallButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VoiceCallButtonActionPerformed

    private void StatusMessageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusMessageComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusMessageComboBoxActionPerformed

    private void SendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessageButtonActionPerformed
        String userMsg = UserMessageText.getText();
        chatMessage = new ChatMessage(userMsg, Boolean.TRUE);
        UserMessageText.setText("");
        chats.add(chatMessage);
        String serverMsg = VirtualHumanConnection.getResponse(userMsg);
        chatMessage = new ChatMessage(serverMsg, Boolean.FALSE);
        chats.add(chatMessage);
        StringBuffer display = new StringBuffer();
        
        for(ChatMessage msg : chats){
            ChatMessage o = (ChatMessage)msg;
            display.append(o.getMessage());
            display.append("\n");
        }
        
        
        JLabel userMessage = new JLabel("UserMessage");
        userMessage.setText(display.toString());
        userMessage.setVisible(true);
        TranscriptScrollPanel.setLayout(FlowLayout);
        TranscriptScrollPanel.setViewportView(userMessage);
        TranscriptScrollPanel.revalidate();
/*
        String serverMsg = VirtualHumanConnection.getResponse(userMsg);
        JLabel serverMessage = new JLabel("ServerMessage");
        serverMessage.setText(serverMsg);
        serverMessage.setVisible(true);
        System.out.println("server resp: " + serverMsg);
        TranscriptScrollPanel.setViewportView(serverMessage);
        TranscriptScrollPanel.revalidate();
        * */
        
    }//GEN-LAST:event_SendMessageButtonActionPerformed

    private void UserMessageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMessageTextActionPerformed
        UserMessageText.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent keyEvent) {
                int key = keyEvent.getKeyCode();
                System.out.println(key);
                if (key == KeyEvent.VK_ENTER) {
                 SendMessageButtonActionPerformed(null);
                }
            }
        });
    }//GEN-LAST:event_UserMessageTextActionPerformed

    private void SearchContactTextBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchContactTextBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchContactTextBox1ActionPerformed

    private void TranscriptScrollPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TranscriptScrollPanelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TranscriptScrollPanelComponentAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JScrollPane ContactsScrollPanel;
    private javax.swing.JComboBox MoreActionsComboBox;
    private javax.swing.JButton SaveChatButton;
    private javax.swing.JTextField SearchContactTextBox;
    private javax.swing.JTextField SearchContactTextBox1;
    private javax.swing.JButton SendMessageButton;
    private javax.swing.JComboBox StatusMessageComboBox;
    private javax.swing.JScrollPane TranscriptScrollPanel;
    private javax.swing.JTextField UserMessageText;
    private javax.swing.JButton VoiceCallButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    // End of variables declaration//GEN-END:variables
}
